# Wrangler configuration for AgarCoin project
name = "agarcoin-frontend"
compatibility_date = "2024-01-01"

# Pages configuration for React frontend
[pages]
# Build command that includes shared package compilation
build_command = "cd client && npm ci && npm run build"
# Output directory where built files are located
build_output_dir = "client/dist"
# Enable source maps for better debugging
source_maps = true

# Environment variables for production
[env.production]
NODE_ENV = "production"

# Build configuration
[build]
# Working directory starts from project root
watch_dir = ["client/src", "shared/src"]
# Upload excludes to reduce bundle size
upload_excludes = [
  "node_modules/**/*",
  "*.log",
  "*.map",
  ".git/**/*",
  ".vscode/**/*",
  ".env*",
  "README.md"
]

# Compatibility flags
compatibility_flags = ["nodejs_compat"]