# Wrangler configuration for AgarCoin project
name = "agarcoin-frontend"
compatibility_date = "2025-10-01"

# Output directory where built files are located (required by Cloudflare Pages)
pages_build_output_dir = "client/dist"

# Pages configuration for React frontend
[pages]
# Build command that includes shared package compilation
# Note: Uses root build command which handles shared dependencies
build_command = "npm run build:shared && npm run build:client"
# Enable source maps for better debugging
source_maps = true

# Environment variables for production
[env.production]
NODE_ENV = "production"

# Build configuration
[build]
# Working directory starts from project root
watch_dir = ["client/src", "shared/src"]
# Upload excludes to reduce bundle size
upload_excludes = [
  "node_modules/**/*",
  "*.log",
  "*.map",
  ".git/**/*",
  ".vscode/**/*",
  ".env*",
  "README.md"
]

# Compatibility flags
compatibility_flags = ["nodejs_compat"]